Repository appneta/tcpreplay, pull requests merged in 2024-06, with the labels that each got.

#478 Add --skip-pkts and --skip-to-secs to allow skipping packets when replaying
  src/send_packets.c
  src/tcpreplay_api.c
  src/tcpreplay_api.h
  src/tcpreplay_opts.def
Labels: enhancement

#846 Add option to turn on/off fix packet header length
  src/tcpedit/parse_args.c
  src/tcpedit/tcpedit.c
  src/tcpedit/tcpedit_api.c
  src/tcpedit/tcpedit_api.h
  src/tcpedit/tcpedit_opts.def
  src/tcpedit/tcpedit_types.h
  src/tcpreplay_api.h
Labels: feature

#847 some Haiku support
  configure.ac
  src/common/sendpacket.h
Labels: enhancement

#849 configure.ac: do not run conftest in case of cross compilation
  configure.ac
Labels: enhancement

#851 dlt_jnpr_ether_cleanup: check config before cleanup
  src/tcpedit/plugins/dlt_jnpr_ether/jnpr_ether.c
Labels: bug

#855 Fix recursive tcpedit cleanup
  src/tcpedit/plugins/dlt_plugins.c
Labels: bug

#868 Bug #867 - run regfree() on close
  docs/CHANGELOG
  src/tcpprep.c
Labels: bug

#870 Bug #869 tcpprep memory leak include exclude
  .github/workflows/github-actions-ci.yml
  docs/CHANGELOG
  src/tcpprep.c
  src/tcpprep_api.c
Labels: bug

#872 Bug #811 - add check for invalid jnpr header length
  src/tcpedit/plugins/dlt_jnpr_ether/jnpr_ether.c
Labels: bug

#873 Bug #792 avoid assertion and other fixes
  docs/CHANGELOG
  src/tcpedit/plugins/dlt_en10mb/en10mb.c
Labels: bug

#874 Bug #844 tap: ignore TUNSETIFF EBUSY errors
  docs/CHANGELOG
  src/common/sendpacket.c
Labels: bug

#877 Bug #876 - add missing free_umem_and_xsk function
  docs/CHANGELOG
  docs/INSTALL
  src/tcpedit/tcpedit.c
  src/tcpreplay_api.c
Labels: bug

#879 Feature #878 - add -w / --suppress-warning option
  docs/CHANGELOG
  src/common/err.c
  src/common/err.h
  src/tcpbridge.c
  src/tcpbridge_opts.def
  src/tcpprep.c
  src/tcpprep_api.c
  src/tcpprep_opts.def
  src/tcpreplay_api.c
  src/tcpreplay_opts.def
  src/tcprewrite.c
  src/tcprewrite_opts.def
Labels: enhancement

#880 Bug #835 false unsupported dlt warnings on 802.3 (Ethernet I) and LLC
  docs/CHANGELOG
  src/common/flows.c
  src/common/flows.h
  src/common/get.c
  src/send_packets.c
  src/tcpedit/tcpedit.c
Labels: bug

#885 Feature #884 include exclude options
  docs/CHANGELOG
  src/common/list.c
  src/send_packets.c
  src/tcpreplay_api.c
  src/tcpreplay_api.h
  src/tcpreplay_opts.def
  test/Makefile.am
Labels: feature

#871 Feature #853 direct traffic to pcap
  configure.ac
  docs/CHANGELOG
  src/common/sendpacket.c
  src/common/sendpacket.h
  src/tcpreplay_api.c
  src/tcpreplay_opts.def
  test/Makefile.am
  test/test.replay_exclude
  test/test.replay_include
  test/test.replay_unique_ip
  test/test2.replay_exclude
  test/test2.replay_include
  test/test2.replay_unique_ip
Labels: enhancement
